### ISSUE TITLE
Nested collection of objects

### ISSUE THREAD

**Issue by arunma** [uchuhimo/konf#17]
Newbie to Kotlin and Konf here.  Is there an easier way to achieve mapping the following yaml to the  Spec below: 

Or does the solution involve using the jackson mapper with config.mapper?  Thank you !

```
datasets:
  hive:
    - key: transactions
      uri: /user/somepath
      format: parquet
      database: transations_daily
      table: transx

    - key: second_transactions
      uri: /seconduser/somepath
      format: avro
      database: transations_monthly
      table: avro_table
  file:
    - key: users
      uri: s3://filestore
      format: parquet
      mode: overwrite
```

```
object DataSetsSpec: ConfigSpec("datasets"){
    val fileDataSets by optional<List<FileDS>>(default = emptyList())
    val hive by optional<List<HiveDS>>(default = emptyList())
}

object FileDS: ConfigSpec ("file"){
    val key by required<String>(description = "Name of the dataset")
    val uri by required<String>(description = "Target path of the file with the protocol qualifier")
    val format by optional<String>("parquet", "File format", "Format in which the file must be writte")
    val mode by optional<String>("append", "Save Mode", "Mode in which the file would be written - (overwrite, append)")
}

object HiveDS: ConfigSpec ("hive"){
    val key by required<String>()
    val uri by required<String>()
    val database by required<String>()
    val table by required<String>()
    val format by optional<String>("parquet", "File format", "Format in which the file must be writte")
    val mode by optional<String>("append", "Save Mode", "Mode in which the file would be written - (overwrite, append)")
}
```

**Comment by uchuhimo** [comment]
@arunma You can use Kotlin data class for nested objects in collections. Konf will handle all the serialization stuff. Here is a runnable solution for your case:

```kotlin
import com.uchuhimo.konf.Config
import com.uchuhimo.konf.ConfigSpec

val text = """
datasets:
  hive:
    - key: transactions
      uri: /user/somepath
      format: parquet
      database: transations_daily
      table: transx

    - key: second_transactions
      uri: /seconduser/somepath
      format: avro
      database: transations_monthly
      table: avro_table
  file:
    - key: users
      uri: s3://filestore
      format: parquet
      mode: overwrite
""".trimIndent()

object DatasetsSpec: ConfigSpec() {
    val file by optional<List<FileDS>>(default = emptyList())
    val hive by optional<List<HiveDS>>(default = emptyList())
}

data class FileDS(val key: String, val uri: String, val format: String = "parquet", val mode: String = "append")

data class HiveDS(val key: String, val uri: String, val database: String, val table: String,  val format: String = "parquet", val mode: String = "append")

fun main(args: Array<String>) {
    val config = Config { addSpec(DatasetsSpec) }.from.yaml.string(text)
    check(config[DatasetsSpec.file][0].key == "users")
    check(config[DatasetsSpec.hive][1].database == "transations_monthly")
}
```

**Comment by arunma** [comment]
@uchuhimo This is excellent !  Love the library.  Thanks a lot !!

**Comment by yashar-sb-sb** [comment]
@uchuhimo 
This way you can't have optional items?

**Comment by uchuhimo** [comment]
@yashar-sb-sb You can provide default value to Kotlin data class's field, which is equivalent to use optional items. Or can you provide an example in which Konf cannot work?

**Comment by drejc** [comment]
Is there a way to name properties in Kotlin data class?
For instance we have a YAML

```yaml
servers:
  server:
    host: 
    time-out: 5
```

and a data class:

`Server(val host: String, timeOut: Int) `

How would one bind `timeOut` to "time-out" ?
