### ISSUE TITLE
TOML Table array mapping

### ISSUE THREAD

**Issue by Cubxity** [uchuhimo/konf#39]
Hey, I've been trying to map toml table array but it returns an empty list.

TOML:
```toml
[[editors]]
id = "bytespy.jvm.bytecode.editor"
impl = "dev.cubxity.bytespy.jvm.impl.editor.BytecodeContentEditor"
content = "org.objectweb.asm.tree.ClassNode"
description = "JVM Bytecode editor"

[[editors]]
id = "bytespy.jvm.bytecode.decompiler"
impl = "dev.cubxity.bytespy.jvm.impl.editor.DecompiledContentEditor"
content = "org.objectweb.asm.tree.ClassNode"
description = "JVM Bytecode decompiler"
```

ConfigSpec:
```kotlin
object ManifestSpec : ConfigSpec() {
    val editors by optional(listOf<Editor>())
}
```

Editor:
```kotlin
data class Editor (
     val id: String,
     val impl: String,
     val content: String,
     val description: String
)
```

Any help would be appreciated :)

**Comment by Cubxity** [comment]
@uchuhimo

**Comment by uchuhimo** [comment]
@Cubxity Konf infers prefix from the name of spec. For `ManifestSpec`, it will infer that the prefix is "manifest". Therefore, either change the ConfigSpec to disable the inference mechanism:

```kotlin
object ManifestSpec : ConfigSpec("") {
    val editors by optional(listOf<Editor>())
}
```

or change the TOML file:

```toml
[[manifest.editors]]
id = "bytespy.jvm.bytecode.editor"
impl = "dev.cubxity.bytespy.jvm.impl.editor.BytecodeContentEditor"
content = "org.objectweb.asm.tree.ClassNode"
description = "JVM Bytecode editor"

[[manifest.editors]]
id = "bytespy.jvm.bytecode.decompiler"
impl = "dev.cubxity.bytespy.jvm.impl.editor.DecompiledContentEditor"
content = "org.objectweb.asm.tree.ClassNode"
description = "JVM Bytecode decompiler"
```
