### ISSUE TITLE
Top-level lists

### ISSUE THREAD

**Issue by gdude2002** [uchuhimo/konf#58]
Does Konf support top-level lists in, for example, YAML files?

```yaml
- 
	key: value
	otherkey: value

-
	key: value
	otherkey: value
```

I couldn't find any documentation on this specific use-case - in my case, I can't modify the file to add a root key. Any chance of support for this?
