### ISSUE TITLE
validateRequired enhancements

### ISSUE THREAD

**Issue by drejc** [uchuhimo/konf#60]
1. `config.validateRequired()` does not check for empty values only nulls
1. the throw UnsetValueException holds only item `name`, does not telling which exact item is not set.

For instance if you have a configuration like this:
```yaml
host:
   url:
   port:

database:
   url:
   port:
```
UnsetValueException will for instance throw **"item url not set"**, better would be **"host.url not set"**
