### ISSUE TITLE
How to prevent konf-yaml from converting keys

### ISSUE THREAD

**Issue by ksqsf** [uchuhimo/konf#66]
For this config,

```
patches:
  matrix:
    attr_idx: [1, 2, 3]
# quoting "attr_idx" doesn't help
```

and this schema

```
    object Patches: ConfigSpec() {
        val matrix by optional(mapOf<String, Map<String, List<String>>>())
    }
```

I noticed `attr_idx` becomes `attrIdx` if I read the config by `cfg[Patches.matrix]`, and hence `cfg[Patches.matrix]["attr_idx"]` fails. How to prevent this behavior for maps?

**Comment by uchuhimo** [comment]
@ksqsf You can use `config.disable(Feature.LOAD_KEYS_AS_LITTLE_CAMEL_CASE)` before loading sources.

**Comment by ksqsf** [comment]
Thanks for your quick reply! However, that makes other parts of the config no longer work.

```yaml
project_name: xxx
patches:
  matrix:
    attr_idx: [1,2,3]
```

and `cfg[Spec.projectName]` now complains `item projectName unset`. Is there a way to disable the feature only for some (subset, or subtree) of the keys, not the whole config?
