### ISSUE TITLE
add support for Maps with enum keys

### ISSUE THREAD

**Issue by Leopard2A5** [uchuhimo/konf#73]
It'd be great to allow something like this:

```kotlin
object MyConfig : ConfigSpec() {
    val foo by required<Map<MyEnum, String>>()
}

enum class MyEnum {
    FOO,
    BAR,
}
```

```yaml
myConfig:
  FOO: hey
  BAR: ho
```
